# Change these first
owner: cypwn
repo: cypwn

sites:
  - name: CyPwn
    url: https://cypwn.xyz
  - name: Repo
    url: https://repo.cypwn.xyz
  - name: IPA Library
    url: https://ipa.cypwn.xyz
  - name: DRM
    url: https://drm.cypwn.xyz
  - name: API
    url: https://api.cypwn.xyz

status-website:
  cname: status.cypwn.xyz
  theme: dark
  logoUrl: https://repo.cypwn.xyz/assets/images/cypwn_small.png
  name: CyPwn Status
  introTitle: "**CyPwn** Services Status"
  introMessage: Join our [Discord](https://discord.gg/cypwn)
  navbar:
    - title: Status
      href: /
    - title: Repo
      href: https://repo.cypwn.xyz
    - title: IPA Library
      href: https://ipa.cypwn.xyz
    - title: Discord
      href: https://discord.gg/cypwn
